### ISSUE TITLE
命名空间不存在

### ISSUE THREAD

**Issue by goyzhang** [blueskit/MitsubishiPlcProtocol#1]
导入项目之后很多标红的命名空间和类呢？
比如：InControls.Common
InControls.IO.Common;
InControls.IO.SerialDevice;
这些在项目里都没有啊？还有那个vila什么的

**Comment by jackswei** [comment]
希望可以修正一下 
using InControls.IO.Common;
using InControls.IO.SerialDevice;
using Vila.Communication.Common;
using Vila.Communication.Net;
using Vila.Threading;
using Vila.Threading.Queue;
上面都不存在，謝謝
