### ISSUE TITLE
關於 ResponseMessage 的使用

### ISSUE THREAD

**Issue by 1TTT9** [blueskit/MitsubishiPlcProtocol#4]
感謝您的開源。想請教一下, 由於 Execute 函數使用後回覆一長串 raw data 信息, 見到您撰寫的 ResponseMessage 物件可沒有使用, 請問該如何判斷並僅取出 read 後的 value 呢?

**Comment by blueskit** [comment]
其实，这些内容已经在 readSingle、readBatch 等函数中按预期的格式解析出来了。
至于其中的原始的数据，仅供后续调试使用（可以忽略）
